// Harissa64 V2 - cartridge save media and the Controller Pak.
//
// Behaviour from n64brew ("Joybus Protocol", "EEPROM", "Controller Pak",
// "FlashRAM") and mupen64plus-core (GPL v2: device/cart/flashram.c, the
// FlashRAM command set and status words; device/controllers/paks/mempak.c,
// the formatted pak image). Save types come from mupen64plus's ROM catalogue
// (h64_savedb.inc, generated by tests/scripts/gen_savedb.py). See THIRD_PARTY.md.
#include "h64_save.h"

#include <stdio.h>
#include <string.h>

#include "../common/h64_endian.h"
#include "../common/h64_log.h"

// ---- Save type ----
struct SaveDbEntry { u32 crc1, crc2; u8 type, pak; };
static const SaveDbEntry s_saveDb[] = {
#include "h64_savedb.inc"
};

int h64_save_type_for_rom(const H64Rom *rom, int *pak)
{
    int lo = 0, hi = (int)(sizeof(s_saveDb) / sizeof(s_saveDb[0])) - 1;
    *pak = 1;
    // Homebrew header (n64brew "ROM header"): "ED" at 0x3C, save type in the high nibble of 0x3F.
    if (rom->size >= 0x40 && rom->data[0x3C] == 'E' && rom->data[0x3D] == 'D')
    {
        static const int types[7] = { H64_SAVE_NONE, H64_SAVE_EEPROM_4K, H64_SAVE_EEPROM_16K, H64_SAVE_SRAM,
                                      H64_SAVE_SRAM, H64_SAVE_FLASH, H64_SAVE_SRAM };
        int t = rom->data[0x3F] >> 4;
        return t < 7 ? types[t] : H64_SAVE_AUTO;
    }
    while (lo <= hi)   // the table is sorted by CRC1, then CRC2
    {
        int mid = (lo + hi) / 2;
        const SaveDbEntry *e = &s_saveDb[mid];
        if (e->crc1 == rom->crc1 && e->crc2 == rom->crc2)
        {
            *pak = e->pak;
            return e->type;
        }
        if (e->crc1 < rom->crc1 || (e->crc1 == rom->crc1 && e->crc2 < rom->crc2)) lo = mid + 1;
        else hi = mid - 1;
    }
    return H64_SAVE_AUTO;
}

const char *h64_save_type_name(int type)
{
    switch (type)
    {
    case H64_SAVE_NONE: return "none";
    case H64_SAVE_EEPROM_4K: return "EEPROM 4 Kbit";
    case H64_SAVE_EEPROM_16K: return "EEPROM 16 Kbit";
    case H64_SAVE_SRAM: return "SRAM";
    case H64_SAVE_FLASH: return "FlashRAM";
    default: return "unknown (EEPROM 4 Kbit, SRAM or FlashRAM)";
    }
}

// ---- Controller Pak ----
// A formatted, empty pak (n64brew "Controller Pak"; the image mupen64plus
// formats): label, ID block and its three backups on page 0, the index table
// and its backup on pages 1 and 2 (all pages free: 0x0003), notes empty.
static void pak_format(u8 *pak)
{
    static const u8 idOffsets[4] = { 0x20, 0x60, 0x80, 0xC0 };
    u8 id[32];
    u32 sum = 0;
    int i, k;
    memset(pak, 0, H64_PAK_SIZE);
    pak[0] = 0x81;
    for (i = 1; i < 0x20; i++) pak[i] = (u8)i;
    memset(id, 0xFF, sizeof(id));
    id[4] = 0x05; id[5] = 0x1A; id[6] = 0x5F; id[7] = 0x13;
    memset(id + 8, 0, 8);
    id[26] = 0x01;   // banks
    for (i = 0; i < 28; i += 2) sum += h64_load_be16(id + i);
    h64_store_be16(id + 28, (u16)sum);
    h64_store_be16(id + 30, (u16)(0xFFF2u - sum));
    for (k = 0; k < 4; k++) memcpy(pak + idOffsets[k], id, sizeof(id));
    for (k = 1; k <= 2; k++)
    {
        u8 *index = pak + k * 0x100;
        u32 check = 0;
        for (i = 5; i < 128; i++)
        {
            index[i * 2 + 1] = 0x03;
            check += 0x03;
        }
        index[1] = (u8)check;
    }
}

u8 h64_save_pak_crc(const u8 *data, int len)
{
    u8 crc = 0;
    int i, b;
    for (i = 0; i < len; i++)
    {
        crc ^= data[i];
        for (b = 0; b < 8; b++) crc = (u8)((crc & 0x80) ? (crc << 1) ^ 0x85 : crc << 1);
    }
    return crc;
}

int h64_save_pak_command(H64SaveMem *s, const u8 *tx, int txLen, u8 *rx, int rxLen)
{
    u32 addr;
    if (!s->pak || txLen < 3) return -1;
    addr = ((u32)tx[1] << 8 | tx[2]) & 0xFFE0u;   // low 5 bits: the address CRC
    if (tx[0] == 0x02 && rxLen >= 33)   // read 32 bytes
    {
        if (addr < H64_PAK_SIZE) memcpy(rx, s->pakData + addr, 32);
        else memset(rx, 0, 32);   // accessory area: no rumble motor here
        rx[32] = h64_save_pak_crc(rx, 32);
        s->used |= H64_SAVE_DIRTY_PAK;
        return 33;
    }
    if (tx[0] == 0x03 && txLen >= 35 && rxLen >= 1)   // write 32 bytes
    {
        if (addr < H64_PAK_SIZE && memcmp(s->pakData + addr, tx + 3, 32))
        {
            memcpy(s->pakData + addr, tx + 3, 32);
            s->dirty |= H64_SAVE_DIRTY_PAK;
        }
        s->used |= H64_SAVE_DIRTY_PAK;
        rx[0] = h64_save_pak_crc(tx + 3, 32);
        return 1;
    }
    return -1;
}

// ---- EEPROM (JoyBus channel 4) ----
static u32 eeprom_size(const H64SaveMem *s) { return s->type == H64_SAVE_EEPROM_16K ? 0x800u : 0x200u; }

int h64_save_eeprom_command(H64SaveMem *s, const u8 *tx, int txLen, u8 *rx, int rxLen)
{
    u32 size = eeprom_size(s), at;
    if (s->type != H64_SAVE_EEPROM_4K && s->type != H64_SAVE_EEPROM_16K && s->type != H64_SAVE_AUTO) return -1;
    if (txLen < 1) return -1;
    switch (tx[0])
    {
    case 0x00:   // info
    case 0xFF:   // reset + info
        if (rxLen < 3) return -1;
        rx[0] = 0x00;
        rx[1] = s->type == H64_SAVE_EEPROM_16K ? 0xC0 : 0x80;
        rx[2] = 0x00;
        return 3;
    case 0x04:   // read 8 bytes
        if (txLen < 2 || rxLen < 8) return -1;
        at = (tx[1] * 8u) & (size - 1);
        memcpy(rx, s->eeprom + at, 8);
        s->used |= H64_SAVE_DIRTY_EEPROM;
        return 8;
    case 0x05:   // write 8 bytes
        if (txLen < 10) return -1;
        at = (tx[1] * 8u) & (size - 1);
        if (memcmp(s->eeprom + at, tx + 2, 8))
        {
            memcpy(s->eeprom + at, tx + 2, 8);
            s->dirty |= H64_SAVE_DIRTY_EEPROM;
        }
        s->used |= H64_SAVE_DIRTY_EEPROM;
        if (rxLen >= 1) rx[0] = 0x00;   // not busy
        return rxLen >= 1 ? 1 : 0;
    }
    return -1;   // real-time clock (0x06-0x08): not on these cartridges
}

// ---- SRAM and FlashRAM (domain 2) ----
enum { FLASH_MODE_IDLE = 0, FLASH_MODE_READ, FLASH_MODE_STATUS, FLASH_MODE_ERASE, FLASH_MODE_WRITE };
#define FLASH_ID 0x00C2001Eull   // Macronix MX29L1100 (mupen64plus's default)

static int domain2(H64SaveMem *s, u32 cart, int isCommandWrite)
{
    if (s->domain2 == H64_SAVE_AUTO)
    {
        // Unknown cartridge: a FlashRAM command first means FlashRAM, anything else SRAM.
        s->domain2 = isCommandWrite ? H64_SAVE_FLASH : H64_SAVE_SRAM;
        H64_INFO("[save] cartridge save memory detected: %s", h64_save_type_name(s->domain2));
    }
    (void)cart;
    return s->domain2;
}

static void flash_command(H64SaveMem *s, u32 cmd)
{
    u32 i;
    switch (cmd >> 24)
    {
    case 0x4B:   // sector erase: page offset
        s->flashMode = FLASH_MODE_ERASE;
        s->flashOffset = (cmd & 0xFFFF) * 128u;
        break;
    case 0x3C:   // chip erase
        s->flashMode = FLASH_MODE_ERASE;
        s->flashOffset = 0xFFFFFFFFu;
        break;
    case 0x78:   // erase mode
        s->flashMode = FLASH_MODE_ERASE;
        s->flashStatus = 0x1111800800000000ull | FLASH_ID;
        break;
    case 0xA5:   // program: page offset
        s->flashOffset = (cmd & 0xFFFF) * 128u;
        s->flashStatus = 0x1111800400000000ull | FLASH_ID;
        break;
    case 0xB4:   // write mode: the next DMA fills the page buffer
        s->flashMode = FLASH_MODE_WRITE;
        break;
    case 0xD2:   // execute
        if (s->flashMode == FLASH_MODE_ERASE)
        {
            if (s->flashOffset == 0xFFFFFFFFu) memset(s->flash, 0xFF, H64_FLASH_SIZE);
            else
                for (i = 0; i < 128; i++) s->flash[(s->flashOffset + i) & (H64_FLASH_SIZE - 1)] = 0xFF;
            s->dirty |= H64_SAVE_DIRTY_FLASH;
        }
        else if (s->flashMode == FLASH_MODE_WRITE)
        {
            for (i = 0; i < 128; i++) s->flash[(s->flashOffset + i) & (H64_FLASH_SIZE - 1)] = s->flashPage[i];
            s->dirty |= H64_SAVE_DIRTY_FLASH;
        }
        break;
    case 0xE1:   // status mode
        s->flashMode = FLASH_MODE_STATUS;
        s->flashStatus = 0x1111800100000000ull | FLASH_ID;
        break;
    case 0xF0:   // read mode
        s->flashMode = FLASH_MODE_READ;
        s->flashStatus = 0x11118004F0000000ull;
        break;
    default:
        H64_DEBUG("[save] FlashRAM: unknown command %08X", cmd);
        break;
    }
}

int h64_save_read32(H64SaveMem *s, u32 cart, u32 *value)
{
    switch (domain2(s, cart, 0))
    {
    case H64_SAVE_SRAM:
        s->used |= H64_SAVE_DIRTY_SRAM;
        *value = h64_load_be32(s->sram + ((cart - 0x08000000u) & (H64_SRAM_SIZE - 4)));
        return 1;
    case H64_SAVE_FLASH:
        s->used |= H64_SAVE_DIRTY_FLASH;
        *value = (u32)(s->flashStatus >> 32);
        return 1;
    }
    return 0;
}

int h64_save_write32(H64SaveMem *s, u32 cart, u32 value)
{
    switch (domain2(s, cart, cart == 0x08010000u))
    {
    case H64_SAVE_SRAM:
        {
            u8 *p = s->sram + ((cart - 0x08000000u) & (H64_SRAM_SIZE - 4));
            if (h64_load_be32(p) != value) { h64_store_be32(p, value); s->dirty |= H64_SAVE_DIRTY_SRAM; }
            s->used |= H64_SAVE_DIRTY_SRAM;
        }
        return 1;
    case H64_SAVE_FLASH:
        s->used |= H64_SAVE_DIRTY_FLASH;
        if (cart == 0x08010000u) flash_command(s, value);
        return 1;
    }
    return 0;
}

int h64_save_dma_to_rdram(H64SaveMem *s, u32 cart, u8 *dst, u32 len)
{
    u32 i;
    switch (domain2(s, cart, 0))
    {
    case H64_SAVE_SRAM:
        for (i = 0; i < len; i++) dst[i] = s->sram[(cart - 0x08000000u + i) & (H64_SRAM_SIZE - 1)];
        s->used |= H64_SAVE_DIRTY_SRAM;
        return 1;
    case H64_SAVE_FLASH:
        s->used |= H64_SAVE_DIRTY_FLASH;
        if (s->flashMode == FLASH_MODE_READ)
        {
            // FlashRAM is addressed in halfwords on the bus.
            u32 at = ((cart - 0x08000000u) & 0xFFFFu) * 2;
            for (i = 0; i < len; i++) dst[i] = s->flash[(at + i) & (H64_FLASH_SIZE - 1)];
        }
        else
            for (i = 0; i < len; i++) dst[i] = (u8)(s->flashStatus >> (56 - 8 * (i & 7)));
        return 1;
    }
    return 0;
}

int h64_save_dma_from_rdram(H64SaveMem *s, u32 cart, const u8 *src, u32 len)
{
    u32 i;
    switch (domain2(s, cart, 0))
    {
    case H64_SAVE_SRAM:
        for (i = 0; i < len; i++)
        {
            u8 *p = &s->sram[(cart - 0x08000000u + i) & (H64_SRAM_SIZE - 1)];
            if (*p != src[i]) { *p = src[i]; s->dirty |= H64_SAVE_DIRTY_SRAM; }
        }
        s->used |= H64_SAVE_DIRTY_SRAM;
        return 1;
    case H64_SAVE_FLASH:
        s->used |= H64_SAVE_DIRTY_FLASH;
        if (s->flashMode == FLASH_MODE_WRITE)
            for (i = 0; i < len && i < 128; i++) s->flashPage[i] = src[i];
        return 1;
    }
    return 0;
}

void h64_save_init(H64SaveMem *s, int type, int pak)
{
    memset(s, 0, sizeof(*s));
    s->type = type;
    s->pak = pak;
    s->domain2 = type == H64_SAVE_SRAM || type == H64_SAVE_FLASH || type == H64_SAVE_AUTO ? type : H64_SAVE_NONE;
    memset(s->eeprom, 0xFF, sizeof(s->eeprom));
    memset(s->sram, 0xFF, sizeof(s->sram));
    memset(s->flash, 0xFF, sizeof(s->flash));
    pak_format(s->pakData);
    s->flashStatus = 0x1111800100000000ull | FLASH_ID;
}

// ---- Files ----
void h64_save_folder_name(const H64Rom *rom, char *out, int outSize)
{
    int n = 0, i, space = 0;
    for (i = 0; rom->name[i] && n < 36 && n < outSize - 1; i++)
    {
        char c = rom->name[i];
        int ok = (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_';
        if (!ok) { space = n > 0; continue; }   // any other character becomes one space
        if (space && n < outSize - 2) out[n++] = ' ';
        space = 0;
        out[n++] = c;
    }
    if (n == 0 && outSize > 8)
    {
        sprintf(out, "%08X", rom->crc1);
        n = 8;
    }
    if (n + 5 < outSize)
    {
        int codeOk = 1;
        for (i = 0; i < 4; i++)
        {
            char c = rom->gameCode[i];
            if (!((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9'))) codeOk = 0;
        }
        if (codeOk)
        {
            out[n++] = ' ';
            for (i = 0; i < 4; i++) out[n++] = rom->gameCode[i];
        }
    }
    out[n] = 0;
}

struct SaveFile { const char *name; u32 bit; };
static const SaveFile s_files[4] = {
    { "eeprom.bin", H64_SAVE_DIRTY_EEPROM },
    { "sram.bin", H64_SAVE_DIRTY_SRAM },
    { "flash.bin", H64_SAVE_DIRTY_FLASH },
    { "pak1.bin", H64_SAVE_DIRTY_PAK },
};

static u8 *file_data(H64SaveMem *s, int k, u32 *size)
{
    switch (k)
    {
    case 0: *size = eeprom_size(s); return s->eeprom;
    case 1: *size = H64_SRAM_SIZE; return s->sram;
    case 2: *size = H64_FLASH_SIZE; return s->flash;
    default: *size = H64_PAK_SIZE; return s->pakData;
    }
}

static int join_path(char *out, size_t outSize, const char *dir, const char *name)
{
    size_t a = strlen(dir), b = strlen(name);
    if (a + b + 1 > outSize) return 0;
    memcpy(out, dir, a);
    memcpy(out + a, name, b + 1);
    return 1;
}

int h64_save_load(H64SaveMem *s, const char *dir)
{
    int k, count = 0;
    for (k = 0; k < 4; k++)
    {
        char path[512];
        u32 size;
        u8 *data = file_data(s, k, &size);
        FILE *f;
        if (!join_path(path, sizeof(path), dir, s_files[k].name)) continue;
        f = fopen(path, "rb");
        if (!f) continue;
        if (fread(data, 1, size, f) > 0)
        {
            s->used |= s_files[k].bit;
            count++;
            H64_INFO("[save] loaded %s", path);
        }
        fclose(f);
    }
    return count;
}

int h64_save_store(H64SaveMem *s, const char *dir)
{
    int k, count = 0;
    for (k = 0; k < 4; k++)
    {
        char path[512];
        u32 size;
        u8 *data = file_data(s, k, &size);
        FILE *f;
        if (!(s->used & s_files[k].bit) || !(s->dirty & s_files[k].bit)) continue;
        if (!join_path(path, sizeof(path), dir, s_files[k].name)) continue;
        f = fopen(path, "wb");
        if (!f || fwrite(data, 1, size, f) != size)
        {
            if (f) fclose(f);
            H64_WARN("[save] could not write %s", path);
            return -1;
        }
        fclose(f);
        s->dirty &= ~s_files[k].bit;
        count++;
        H64_INFO("[save] wrote %s", path);
    }
    return count;
}
