// Generated by tests/scripts/gen_ppc_emit_test.py from GNU as (powerpc64-linux-gnu-as): do not edit.
#include "unit_tests.h"

#include "../../core/dynarec/h64_ppc_emit.h"

void test_ppc_emit(H64TestContext *ctx)
{
    u32 buf[4];
    H64PpcCode c;
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_addi(&c, 3, 4, -5);
    H64_CHECK_EQ(ctx, buf[0], 0x3864FFFBu);   // addi 3,4,-5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_addis(&c, 3, 4, 0x1234);
    H64_CHECK_EQ(ctx, buf[0], 0x3C641234u);   // addis 3,4,0x1234
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_li(&c, 3, 42);
    H64_CHECK_EQ(ctx, buf[0], 0x3860002Au);   // li 3,42
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lis(&c, 3, -32768);
    H64_CHECK_EQ(ctx, buf[0], 0x3C608000u);   // lis 3,-32768
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_ori(&c, 3, 4, 0xBEEF);
    H64_CHECK_EQ(ctx, buf[0], 0x6083BEEFu);   // ori 3,4,0xBEEF
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_oris(&c, 3, 4, 0xBEEF);
    H64_CHECK_EQ(ctx, buf[0], 0x6483BEEFu);   // oris 3,4,0xBEEF
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_xori(&c, 3, 4, 7);
    H64_CHECK_EQ(ctx, buf[0], 0x68830007u);   // xori 3,4,7
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_xoris(&c, 3, 4, 7);
    H64_CHECK_EQ(ctx, buf[0], 0x6C830007u);   // xoris 3,4,7
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_andi_(&c, 3, 4, 0xFF);
    H64_CHECK_EQ(ctx, buf[0], 0x708300FFu);   // andi. 3,4,0xFF
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_andis_(&c, 3, 4, 0xFF);
    H64_CHECK_EQ(ctx, buf[0], 0x748300FFu);   // andis. 3,4,0xFF
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mulli(&c, 3, 4, -3);
    H64_CHECK_EQ(ctx, buf[0], 0x1C64FFFDu);   // mulli 3,4,-3
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_subfic(&c, 3, 4, 31);
    H64_CHECK_EQ(ctx, buf[0], 0x2064001Fu);   // subfic 3,4,31
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_add(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642A14u);   // add 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_subf(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642850u);   // subf 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_neg(&c, 3, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x7C6400D0u);   // neg 3,4
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mullw(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C6429D6u);   // mullw 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mulhw(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642896u);   // mulhw 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mulhwu(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642816u);   // mulhwu 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mulld(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C6429D2u);   // mulld 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mulhd(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642892u);   // mulhd 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mulhdu(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642812u);   // mulhdu 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_divw(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642BD6u);   // divw 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_divwu(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642B96u);   // divwu 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_divd(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642BD2u);   // divd 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_divdu(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642B92u);   // divdu 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_and(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832838u);   // and 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_andc(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832878u);   // andc 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_or(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832B78u);   // or 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mr(&c, 3, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832378u);   // mr 3,4
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_xor(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832A78u);   // xor 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_nor(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C8328F8u);   // nor 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_extsb(&c, 3, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x7C830774u);   // extsb 3,4
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_extsh(&c, 3, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x7C830734u);   // extsh 3,4
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_extsw(&c, 3, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x7C8307B4u);   // extsw 3,4
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_slw(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832830u);   // slw 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_srw(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832C30u);   // srw 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_sraw(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832E30u);   // sraw 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_srawi(&c, 3, 4, 7);
    H64_CHECK_EQ(ctx, buf[0], 0x7C833E70u);   // srawi 3,4,7
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_sld(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832836u);   // sld 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_srd(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832C36u);   // srd 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_srad(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C832E34u);   // srad 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_sradi(&c, 3, 4, 7);
    H64_CHECK_EQ(ctx, buf[0], 0x7C833E74u);   // sradi 3,4,7
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_sradi(&c, 3, 4, 45);
    H64_CHECK_EQ(ctx, buf[0], 0x7C836E76u);   // sradi 3,4,45
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_rlwinm(&c, 3, 4, 5, 6, 7);
    H64_CHECK_EQ(ctx, buf[0], 0x5483298Eu);   // rlwinm 3,4,5,6,7
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_rldicl(&c, 3, 4, 5, 6);
    H64_CHECK_EQ(ctx, buf[0], 0x78832980u);   // rldicl 3,4,5,6
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_rldicl(&c, 3, 4, 40, 50);
    H64_CHECK_EQ(ctx, buf[0], 0x788344A2u);   // rldicl 3,4,40,50
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_rldicr(&c, 3, 4, 5, 6);
    H64_CHECK_EQ(ctx, buf[0], 0x78832984u);   // rldicr 3,4,5,6
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_rldicr(&c, 3, 4, 33, 40);
    H64_CHECK_EQ(ctx, buf[0], 0x78830A26u);   // rldicr 3,4,33,40
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_rldimi(&c, 3, 4, 32, 0);
    H64_CHECK_EQ(ctx, buf[0], 0x7883000Eu);   // rldimi 3,4,32,0
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_sldi(&c, 3, 4, 32);
    H64_CHECK_EQ(ctx, buf[0], 0x788307C6u);   // sldi 3,4,32
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_srdi(&c, 3, 4, 32);
    H64_CHECK_EQ(ctx, buf[0], 0x78830022u);   // srdi 3,4,32
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_clrldi(&c, 3, 4, 32);
    H64_CHECK_EQ(ctx, buf[0], 0x78830020u);   // clrldi 3,4,32
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_cmpw(&c, 0, 3, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x7C032000u);   // cmpw 0,3,4
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_cmpd(&c, 1, 3, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x7CA32000u);   // cmpd 1,3,4
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_cmplw(&c, 0, 3, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x7C032040u);   // cmplw 0,3,4
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_cmpld(&c, 7, 3, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x7FA32040u);   // cmpld 7,3,4
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_cmpwi(&c, 0, 3, -5);
    H64_CHECK_EQ(ctx, buf[0], 0x2C03FFFBu);   // cmpwi 0,3,-5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_cmpdi(&c, 0, 3, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x2C230005u);   // cmpdi 0,3,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_cmplwi(&c, 0, 3, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x28030005u);   // cmplwi 0,3,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_cmpldi(&c, 0, 3, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x28230005u);   // cmpldi 0,3,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lbz(&c, 3, -8, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x8864FFF8u);   // lbz 3,-8(4)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lhz(&c, 3, 8, 4);
    H64_CHECK_EQ(ctx, buf[0], 0xA0640008u);   // lhz 3,8(4)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lha(&c, 3, 8, 4);
    H64_CHECK_EQ(ctx, buf[0], 0xA8640008u);   // lha 3,8(4)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lwz(&c, 3, 8, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x80640008u);   // lwz 3,8(4)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lwa(&c, 3, 8, 4);
    H64_CHECK_EQ(ctx, buf[0], 0xE864000Au);   // lwa 3,8(4)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_ld(&c, 3, -16, 4);
    H64_CHECK_EQ(ctx, buf[0], 0xE864FFF0u);   // ld 3,-16(4)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_stb(&c, 3, 8, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x98640008u);   // stb 3,8(4)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_sth(&c, 3, 8, 4);
    H64_CHECK_EQ(ctx, buf[0], 0xB0640008u);   // sth 3,8(4)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_stw(&c, 3, 8, 4);
    H64_CHECK_EQ(ctx, buf[0], 0x90640008u);   // stw 3,8(4)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_stwu(&c, 1, -160, 1);
    H64_CHECK_EQ(ctx, buf[0], 0x9421FF60u);   // stwu 1,-160(1)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_std(&c, 3, 16, 4);
    H64_CHECK_EQ(ctx, buf[0], 0xF8640010u);   // std 3,16(4)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_stdu(&c, 1, -160, 1);
    H64_CHECK_EQ(ctx, buf[0], 0xF821FF61u);   // stdu 1,-160(1)
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lbzx(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C6428AEu);   // lbzx 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lhzx(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642A2Eu);   // lhzx 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lhax(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642AAEu);   // lhax 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lwzx(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C64282Eu);   // lwzx 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_lwax(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642AAAu);   // lwax 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_ldx(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C64282Au);   // ldx 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_stbx(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C6429AEu);   // stbx 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_sthx(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C642B2Eu);   // sthx 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_stwx(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C64292Eu);   // stwx 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_stdx(&c, 3, 4, 5);
    H64_CHECK_EQ(ctx, buf[0], 0x7C64292Au);   // stdx 3,4,5
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mflr(&c, 0);
    H64_CHECK_EQ(ctx, buf[0], 0x7C0802A6u);   // mflr 0
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mtlr(&c, 0);
    H64_CHECK_EQ(ctx, buf[0], 0x7C0803A6u);   // mtlr 0
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_mtctr(&c, 12);
    H64_CHECK_EQ(ctx, buf[0], 0x7D8903A6u);   // mtctr 12
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_blr(&c);
    H64_CHECK_EQ(ctx, buf[0], 0x4E800020u);   // blr
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_bctr(&c);
    H64_CHECK_EQ(ctx, buf[0], 0x4E800420u);   // bctr
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_bctrl(&c);
    H64_CHECK_EQ(ctx, buf[0], 0x4E800421u);   // bctrl
    c.buf = buf; c.pos = 0; c.cap = 4; c.overflow = 0; ppc_nop(&c);
    H64_CHECK_EQ(ctx, buf[0], 0x60000000u);   // nop
}
