#!/usr/bin/env python3
"""Generates core/cart/h64_savedb.inc: the save type of each known cartridge,
keyed by the two header CRCs, from mupen64plus's ROM catalogue (the copy V1
ships as files/mupen64plus.ini on the master branch; GPL v2, see
THIRD_PARTY.md). Entries with RefMD5 inherit from the entry they name.

Run (from the repository root): python tests/scripts/gen_savedb.py
"""
import os
import subprocess

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TYPES = {"Eeprom 4KB": "H64_SAVE_EEPROM_4K", "Eeprom 16KB": "H64_SAVE_EEPROM_16K", "SRAM": "H64_SAVE_SRAM",
         "Flash RAM": "H64_SAVE_FLASH", "None": "H64_SAVE_NONE"}


def main():
    text = subprocess.run(["git", "show", "master:files/mupen64plus.ini"], cwd=ROOT, capture_output=True,
                          text=True, encoding="latin-1").stdout
    entries, cur = {}, None
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("[") and line.endswith("]"):
            cur = entries.setdefault(line[1:-1], {})
        elif cur is not None and "=" in line and not line.startswith(";"):
            k, v = line.split("=", 1)
            cur[k.strip()] = v.strip()

    def get(e, key, depth=0):
        if key in e or depth > 4:
            return e.get(key)
        ref = e.get("RefMD5")
        return get(entries[ref], key, depth + 1) if ref in entries else None

    rows = {}
    for md5, e in entries.items():
        crc = e.get("CRC")
        if not crc:
            continue
        save = get(e, "SaveType")
        pak = get(e, "Mempak") == "Yes"
        if save is None and not pak:
            continue
        c1, c2 = (int(x, 16) for x in crc.split())
        rows[(c1, c2)] = (TYPES.get(save or "None", "H64_SAVE_NONE"), pak, get(e, "GoodName") or "")
    out = ["// Generated by tests/scripts/gen_savedb.py from mupen64plus's ROM catalogue: do not edit.",
           "// { header CRC1, header CRC2, save type, Controller Pak }"]
    for (c1, c2), (t, pak, name) in sorted(rows.items()):
        out.append("{ 0x%08Xu, 0x%08Xu, %s, %d },   // %s" % (c1, c2, t, 1 if pak else 0, name.replace("*/", "")[:60]))
    path = os.path.join(ROOT, "core", "cart", "h64_savedb.inc")
    open(path, "w", newline="\n", encoding="ascii", errors="replace").write("\n".join(out) + "\n")
    print("wrote %s (%d entries)" % (path, len(rows)))


if __name__ == "__main__":
    main()
